server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/naverboost?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true # 변경해주세요
    username:  bootuser
    password:  1234
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
#    org.hibernate.type : trace